theme = "catppuccin-latte"

[editor]
auto-completion = true
auto-format = false
auto-pairs = true
bufferline = "never"
color-modes = true
completion-replace = true
end-of-line-diagnostics = "hint"
line-number = "relative"
path-completion = true
preview-completion-insert = true

[editor.buffer-picker]
start-position = "current"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
auto-signature-help = false
display-color-swatches = false
display-inlay-hints = false
enable = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "file-name"]
right = ["spinner", "diagnostics", "selections", "read-only-indicator", "file-modification-indicator"]

[editor.word-completion]
enable = true
trigger-length = 4

[keys.insert]
C-p = "signature_help"

[keys.normal.space]
q = ":quit"

[keys.normal.space.b]
R = ":reload-all"
c = ":bc"
r = ":reload"
w = ":w"

[keys.normal.space.c]
C = "toggle_block_comments"
I = "decrement"
a = "code_action"
c = "toggle_comments"
f = ":format"
h = "select_references_to_symbol_under_cursor"
i = "increment"
l = ":lsp-restart"
r = "rename_symbol"
s = "signature_help"
y = ":yank-diagnostic"

[keys.normal.space.c.t]
T = ["select_all", ":tree-sitter-subtree"]
h = ":tree-sitter-highlight-name"
s = ":tree-sitter-scopes"
t = ":tree-sitter-subtree"

[keys.normal.space.e]
g = ":sh myterminalrun lazygit -p '%{workspace_directory}'"
y = ":sh myterminalrun yazi '%{file_path_absolute}'"

[keys.normal.space.f]
"'" = "last_picker"
"/" = "global_search"
D = "workspace_diagnostics_picker"
E = "file_explorer_in_current_buffer_directory"
F = "file_picker_in_current_buffer_directory"
S = "workspace_symbol_picker"
b = "buffer_picker"
d = "diagnostics_picker"
e = "file_explorer"
f = "file_picker"
g = "changed_file_picker"
j = "jumplist_picker"
s = "symbol_picker"

[keys.normal.space.g]
B = ":echo %sh{git branch --show-current}"
R = ":reset-diff-change"
b = ":sh git -C %{workspace_directory} blame -L %{cursor_line},%{cursor_line} %{file_path_absolute}"

[keys.select.space]
q = ":quit"

[keys.select.space.b]
R = ":reload-all"
c = ":bc"
r = ":reload"
w = ":w"

[keys.select.space.c]
C = "toggle_block_comments"
I = "decrement"
a = "code_action"
c = "toggle_comments"
f = ":format"
h = "select_references_to_symbol_under_cursor"
i = "increment"
l = ":lsp-restart"
r = "rename_symbol"
s = "signature_help"
y = ":yank-diagnostic"

[keys.select.space.c.t]
T = ["select_all", ":tree-sitter-subtree"]
h = ":tree-sitter-highlight-name"
s = ":tree-sitter-scopes"
t = ":tree-sitter-subtree"

[keys.select.space.e]
g = ":sh myterminalrun lazygit -p '%{workspace_directory}'"
y = ":sh myterminalrun yazi '%{file_path_absolute}'"

[keys.select.space.f]
"'" = "last_picker"
"/" = "global_search"
D = "workspace_diagnostics_picker"
E = "file_explorer_in_current_buffer_directory"
F = "file_picker_in_current_buffer_directory"
S = "workspace_symbol_picker"
b = "buffer_picker"
d = "diagnostics_picker"
e = "file_explorer"
f = "file_picker"
g = "changed_file_picker"
j = "jumplist_picker"
s = "symbol_picker"

[keys.select.space.g]
B = ":echo %sh{git branch --show-current}"
R = ":reset-diff-change"
b = ":sh git -C %{workspace_directory} blame -L %{cursor_line},%{cursor_line} %{file_path_absolute}"

