add_newline = false
command_timeout = 30
format = "$all$time$line_break$character"
palette = "catppuccin_latte"
scan_timeout = 30

[character]
error_symbol = "[x](bold red)"
success_symbol = "[>](bold lavender)"
vimcmd_symbol = "[v](bold peach)"

[directory]
style = "bold lavender"
truncate_to_repo = false

[direnv]
disabled = false

[fill]
disabled = false
symbol = " "

[gcloud]
disabled = true

[nix_shell]
format = "via [$symbol$state]($style) "
symbol = "󱄅 "

[palettes.catppuccin_latte]
base = "#eff1f5"
blue = "#1e66f5"
crust = "#dce0e8"
flamingo = "#dd7878"
green = "#40a02b"
lavender = "#7287fd"
mantle = "#e6e9ef"
maroon = "#e64553"
mauve = "#8839ef"
overlay0 = "#9ca0b0"
overlay1 = "#8c8fa1"
overlay2 = "#7c7f93"
peach = "#fe640b"
pink = "#ea76cb"
red = "#d20f39"
rosewater = "#dc8a78"
sapphire = "#209fb5"
sky = "#04a5e5"
subtext0 = "#6c6f85"
subtext1 = "#5c5f77"
surface0 = "#ccd0da"
surface1 = "#bcc0cc"
surface2 = "#acb0be"
teal = "#179299"
text = "#4c4f69"
yellow = "#df8e1d"

[python]
symbol = "󰌠 "

[time]
disabled = false
format = "[($time)](overlay0)"
time_format = "(%H:%M)"
utc_time_offset = "local"
