[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "off"
shape = "Block"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = ["theme.toml", "extra.toml"]
ipc_socket = false
live_config_reload = false

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Alt|Shift"

[scrolling]
history = 1000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2
