[[keyboard.bindings]]
key = "T"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["-e", "wsl", "-d", "NixOS", "--shell-type", "login", "--cd", "~", "--", "tmux", "new"]
program = "alacritty"

[terminal.shell]
args = [
    "-d",
    "NixOS",
    "--shell-type",
    "login",
    "--cd",
    "~",
]
program = "wsl"
