[terminal.shell]
program = "wsl"
args = ["--cd", "~", "--shell-type", "login", "--", "tmux", "new"]

# fix rendering issues in windows: https://github.com/alacritty/alacritty/issues/8236#issuecomment-2408690086
